# (C) 1992-2014 Altera Corporation. All rights reserved.                         
# Your use of Altera Corporation's design tools, logic functions and other       
# software and tools, and its AMPP partner logic functions, and any output       
# files any of the foregoing (including device programming or simulation         
# files), and any associated documentation or information are expressly subject  
# to the terms and conditions of the Altera Program License Subscription         
# Agreement, Altera MegaCore Function License Agreement, or other applicable     
# license agreement, including, without limitation, that your use is for the     
# sole purpose of programming logic devices manufactured by Altera and sold by   
# Altera or its authorized distributors.  Please refer to the applicable         
# agreement for further details.                                                 
    

# TCL File Generated by Component Editor 14.0
# Mon Jan 20 16:06:50 EST 2014
# DO NOT MODIFY


# 
# cpld_bridge "cpld_bridge" v1.0
#  2014.01.20.16:06:50
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module cpld_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME cpld_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME cpld_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CPLDHostTop
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cpld_bridge_top.vhd VHDL PATH cpld_bridge/cpld_bridge_top.vhd TOP_LEVEL_FILE
add_fileset_file cpld_bridge.vhd VHDL PATH cpld_bridge/cpld_bridge.vhd


# 
# parameters
# 


# 
# display items
# 

# 
# connection point cpld_host
# 
add_interface cpld_host conduit end
set_interface_property cpld_host associatedClock cpld_host_clock
set_interface_property cpld_host associatedReset ""
set_interface_property cpld_host ENABLED true
set_interface_property cpld_host EXPORT_OF ""
set_interface_property cpld_host PORT_NAME_MAP ""
set_interface_property cpld_host SVD_ADDRESS_GROUP ""

add_interface_port cpld_host cpldHostIn_oe cpld_oe Input 1
add_interface_port cpld_host cpldHostIn_rd_n cpld_rd_n Input 1
add_interface_port cpld_host cpldHostIn_wr_n cpld_wr_n Input 1
add_interface_port cpld_host cpldHostOut_flags cpld_flags Output 2
add_interface_port cpld_host cpldHostOut_rd_ready_n cpld_rd_ready Output 1
add_interface_port cpld_host cpldHostOut_wr_ready_n cpld_wr_ready Output 1
add_interface_port cpld_host cpldHostInOut_data cpld_inoutdata Bidir 8


# 
# connection point cpld_host_clock
# 
add_interface cpld_host_clock clock end
set_interface_property cpld_host_clock clockRate 0
set_interface_property cpld_host_clock ENABLED true
set_interface_property cpld_host_clock EXPORT_OF ""
set_interface_property cpld_host_clock PORT_NAME_MAP ""
set_interface_property cpld_host_clock SVD_ADDRESS_GROUP ""

add_interface_port cpld_host_clock cpldHostIn_clk clk Input 1


# 
# connection point cpld_mm_in
# 
add_interface cpld_mm_in avalon end
set_interface_property cpld_mm_in addressUnits WORDS
set_interface_property cpld_mm_in associatedClock cpld_mm_in_clock
set_interface_property cpld_mm_in associatedReset cpld_mm_in_reset
set_interface_property cpld_mm_in bitsPerSymbol 8
set_interface_property cpld_mm_in burstOnBurstBoundariesOnly false
set_interface_property cpld_mm_in burstcountUnits WORDS
set_interface_property cpld_mm_in explicitAddressSpan 0
set_interface_property cpld_mm_in holdTime 0
set_interface_property cpld_mm_in linewrapBursts false
set_interface_property cpld_mm_in maximumPendingReadTransactions 1
set_interface_property cpld_mm_in readLatency 0
set_interface_property cpld_mm_in readWaitTime 1
set_interface_property cpld_mm_in setupTime 0
set_interface_property cpld_mm_in timingUnits Cycles
set_interface_property cpld_mm_in writeWaitTime 0
set_interface_property cpld_mm_in ENABLED true
set_interface_property cpld_mm_in EXPORT_OF ""
set_interface_property cpld_mm_in PORT_NAME_MAP ""
set_interface_property cpld_mm_in SVD_ADDRESS_GROUP ""

add_interface_port cpld_mm_in cpldSlaveIn_read read Input 1
add_interface_port cpld_mm_in cpldSlaveIn_write write Input 1
add_interface_port cpld_mm_in cpldSlaveIn_writedata writedata Input 16
add_interface_port cpld_mm_in cpldSlaveInRsp_readdata readdata Output 16
add_interface_port cpld_mm_in cpldSlaveInRsp_readdatavalid readdatavalid Output 1
add_interface_port cpld_mm_in cpldSlaveInRsp_waitrequest waitrequest Output 1
set_interface_assignment cpld_mm_in embeddedsw.configuration.isFlash 0
set_interface_assignment cpld_mm_in embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cpld_mm_in embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cpld_mm_in embeddedsw.configuration.isPrintableDevice 0


# 
# connection point cpld_mm_in_clock
# 
add_interface cpld_mm_in_clock clock end
set_interface_property cpld_mm_in_clock clockRate 0
set_interface_property cpld_mm_in_clock ENABLED true
set_interface_property cpld_mm_in_clock EXPORT_OF ""
set_interface_property cpld_mm_in_clock PORT_NAME_MAP ""
set_interface_property cpld_mm_in_clock SVD_ADDRESS_GROUP ""

add_interface_port cpld_mm_in_clock cpldSlaveClk clk Input 1


# 
# connection point cpld_mm_in_reset
# 
add_interface cpld_mm_in_reset reset end
set_interface_property cpld_mm_in_reset associatedClock cpld_mm_in_clock
set_interface_property cpld_mm_in_reset synchronousEdges DEASSERT
set_interface_property cpld_mm_in_reset ENABLED true
set_interface_property cpld_mm_in_reset EXPORT_OF ""
set_interface_property cpld_mm_in_reset PORT_NAME_MAP ""
set_interface_property cpld_mm_in_reset SVD_ADDRESS_GROUP ""

add_interface_port cpld_mm_in_reset cpldSlaveReset reset Input 1


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock master_clock
set_interface_property master associatedReset master_reset
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 1
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master masterOut_byteenable byteenable Output 8
add_interface_port master masterOut_read read Output 1
add_interface_port master masterOut_write write Output 1
add_interface_port master masterOut_writedata writedata Output 64
add_interface_port master masterOutRsp_readdata readdata Input 64
add_interface_port master masterOutRsp_readdatavalid readdatavalid Input 1
add_interface_port master masterOutRsp_waitrequest waitrequest Input 1
add_interface_port master masterOut_address address Output 40


# 
# connection point master_clock
# 
add_interface master_clock clock end
set_interface_property master_clock clockRate 0
set_interface_property master_clock ENABLED true
set_interface_property master_clock EXPORT_OF ""
set_interface_property master_clock PORT_NAME_MAP ""
set_interface_property master_clock SVD_ADDRESS_GROUP ""

add_interface_port master_clock masterClk clk Input 1


# 
# connection point master_reset
# 
add_interface master_reset reset end
set_interface_property master_reset associatedClock master_clock
set_interface_property master_reset synchronousEdges DEASSERT
set_interface_property master_reset ENABLED true
set_interface_property master_reset EXPORT_OF ""
set_interface_property master_reset PORT_NAME_MAP ""
set_interface_property master_reset SVD_ADDRESS_GROUP ""

add_interface_port master_reset masterReset reset Input 1


# 
# connection point master_irq
# 
add_interface master_irq interrupt start
set_interface_property master_irq associatedAddressablePoint master
set_interface_property master_irq associatedClock master_clock
set_interface_property master_irq associatedReset master_reset
set_interface_property master_irq irqScheme INDIVIDUAL_REQUESTS
set_interface_property master_irq ENABLED true
set_interface_property master_irq EXPORT_OF ""
set_interface_property master_irq PORT_NAME_MAP ""
set_interface_property master_irq SVD_ADDRESS_GROUP ""

add_interface_port master_irq masterIRQ_irq irq Input 2


# 
# connection point csr_irq
# 
add_interface csr_irq interrupt end
set_interface_property csr_irq associatedAddressablePoint csr
set_interface_property csr_irq associatedClock csr_clock
set_interface_property csr_irq associatedReset csr_reset
set_interface_property csr_irq ENABLED true
set_interface_property csr_irq EXPORT_OF ""
set_interface_property csr_irq PORT_NAME_MAP ""
set_interface_property csr_irq SVD_ADDRESS_GROUP ""

add_interface_port csr_irq slaveIRQ_irq irq Output 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock csr_clock
set_interface_property csr associatedReset csr_reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 1
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr slaveIn_address address Input 5
add_interface_port csr slaveIn_byteenable byteenable Input 4
add_interface_port csr slaveIn_read read Input 1
add_interface_port csr slaveIn_write write Input 1
add_interface_port csr slaveIn_writedata writedata Input 32
add_interface_port csr slaveInRsp_readdata readdata Output 32
add_interface_port csr slaveInRsp_readdatavalid readdatavalid Output 1
add_interface_port csr slaveInRsp_waitrequest waitrequest Output 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point csr_clock
# 
add_interface csr_clock clock end
set_interface_property csr_clock clockRate 0
set_interface_property csr_clock ENABLED true
set_interface_property csr_clock EXPORT_OF ""
set_interface_property csr_clock PORT_NAME_MAP ""
set_interface_property csr_clock SVD_ADDRESS_GROUP ""

add_interface_port csr_clock slaveClk clk Input 1


# 
# connection point csr_reset
# 
add_interface csr_reset reset end
set_interface_property csr_reset associatedClock csr_clock
set_interface_property csr_reset synchronousEdges DEASSERT
set_interface_property csr_reset ENABLED true
set_interface_property csr_reset EXPORT_OF ""
set_interface_property csr_reset PORT_NAME_MAP ""
set_interface_property csr_reset SVD_ADDRESS_GROUP ""

add_interface_port csr_reset slaveReset reset Input 1

